In [1]:
import pandas as pd #imported pandas for reading the file

In [2]:
df = pd.read_excel("resume_ranking.xlsx")
df.head() #read the file

,accomplishments_segment,degree,education_segment,emails,job_titles,links,misc_segment,name,objectives_segment,phone,...,text,university_0,university_1,university_2,university_3,university_4,university_5,url,work_experience,work_segment
0,NaN,"MS , B.TECH , PhD",NaN,sutarvinayak2063@gmail.com,"full stack developer , student","https://github.com/ramsuthar305/SIH2019 , http...",NaN,Prasad Nagar,NaN,+919309161108,...,VINAYAK \nSUTAR \nLinkedIn \n+91 9309161108 ...,"national, mainpuri, uttar pradesh","college of arts, sundargarh, odisha","school of engineering, ernakulam, kerala",NaN,NaN,NaN,https://training-resumes.s3.ap-south-1.amazona...,NaN,NaN
1,NaN,"B.E , MS , M.TECH",M.Tech. Data Science\nJSS Science And Technolo...,pooj.vs@gmail.com,software engineer,pooj.vs,06/2017 – 07/2019\n07/2018 – 07/2019\nmailto:p...,Software Engineer,NaN,7411786822,...,POOJA V S\nSoftware Engineer\nRich exposure to...,"government, kandhamal, odisha","vidya vardhaka college of engineering, mysore,...",NaN,NaN,NaN,NaN,https://training-resumes.s3.ap-south-1.amazona...,NaN,Merchandising System' using PL/SQL.\nmaintain ...
2,Successfully cleared and completed the course ...,"MS , B.TECH , BS",Degree\nInstitute\nBoard/University\nYear\nPer...,khandelwal.ashwin5@gmail.com,NaN,https://www.linkedin.com/in/ashwin-khandelwal-...,NaN,Ashwin Khandelwal,"I seek challenging environment to work in, tha...",9462710290,...,Ashwin Khandelwal \n Email id – khand...,"narsee monjee institute of management studies,...",NaN,NaN,NaN,NaN,NaN,https://training-resumes.s3.ap-south-1.amazona...,NaN,Organization / Institute\nDescription\nBharat ...
3,NaN,"B.E , MS , BS",NaN,NaN,"work from home , support analyst , software an...",NaN,NaN,Computer Engineering,NaN,919930485336,...,Assessment\nQ1. Why should you be hired for th...,"master, medak, telangana",NaN,NaN,NaN,NaN,NaN,https://training-resumes.s3.ap-south-1.amazona...,1.0,NaN
4,NaN,"MS , B.TECH , BS",NaN,NaN,"work from home , classifier",https://github.com/ajay1013/Titanic-ML-from-Di...,NaN, Python,NaN,918010295832,...,Assessment\nQ1. Why should you be hired for th...,"greater noida institute of technology, gautam ...",NaN,NaN,NaN,NaN,NaN,https://training-resumes.s3.ap-south-1.amazona...,NaN,NaN

In [3]:
df.shape #no of rows and columns

(1573, 23)

In [4]:
df.info() #information about the columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1573 entries, 0 to 1572
Data columns (total 23 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   accomplishments_segment  66 non-null     object
 1   degree                   1535 non-null   object
 2   education_segment        457 non-null    object
 3   emails                   64 non-null     object
 4   job_titles               1546 non-null   object
 5   links                    1219 non-null   object
 6   misc_segment             22 non-null     object
 7   name                     1572 non-null   object
 8   objectives_segment       414 non-null    object
 9   phone                    1354 non-null   object
 10  projects_segment         680 non-null    object
 11  skills                   1573 non-null   object
 12  skills_segment           468 non-null    object
 13  text                     1573 non-null   object
 14  university_0             566 non-null    object
 15  university_1             268 non-null    object
 16  university_2             93 non-null     object
 17  university_3             28 non-null     object
 18  university_4             5 non-null      object
 19  university_5             2 non-null      object
 20  url                      1573 non-null   object
 21  work_experience          719 non-null    float64
 22  work_segment             680 non-null    object
dtypes: float64(1), object(22)
memory usage: 282.8+ KB

In [5]:
df.isnull().sum() #checking for null values

accomplishments_segment    1507
degree                       38
education_segment          1116
emails                     1509
job_titles                   27
links                       354
misc_segment               1551
name                          1
objectives_segment         1159
phone                       219
projects_segment            893
skills                        0
skills_segment             1105
text                          0
university_0               1007
university_1               1305
university_2               1480
university_3               1545
university_4               1568
university_5               1571
url                           0
work_experience             854
work_segment                893
dtype: int64

In [6]:
a = df['text'][1]
print(str(a)) #printing the text column. I wanted to know exactly what all information it contains

POOJA V S
Software Engineer
Rich exposure to Software Development Life Cycle. Insights into Machine Learning techniques. Adroit at quite a number of tools and
programming languages. Passionate about playing around with data. Hands-on experience with Java, Python and pl/sql programming.
Looking forward to grasp new technologies.
pooj.vs@gmail.com
7411786822
#58, 2nd Main, 4th Cross Nethaji
Layout, Vijayanagara, Bengaluru
- 40, India
22 March, 1994
SKILLS
Java Python C
J2EE SQL HTML
PL/SQL Big Data
Machine Learning
Deep Learning NLP
FRAMEWORKS
Eclipse
Native or Bilingual Proficiency
Jupyter Notebook
Full Professional Proficiency
SQL tools
Full Professional Proficiency
Full Professional Proficiency
Playing Chess
Solving Puzzles
Listening to Music
EDUCATION
M.Tech. Data Science
JSS Science And Technology University, Mysuru
9.15/10
08/2011 – 06/2015
B.E. Information Science and Engineering
Vidya Vardhaka College Of Engineering, Mysuru
71.24%
06/2010 – 06/2011
PU College (Karnataka State Board)
Government PU College, Talakadu
71.16%
06/2008 – 06/2009
Class 10 (Karnataka State Board)
Government High School, Talakadu
76.80%
WORK EXPERIENCE
Project Intern
Oracle India Private Limited
Bengaluru
Worked on improving the accessibility for the Oracle Retail product 'Oracle Retail
Merchandising System' using PL/SQL.
maintain the issues, which are fixed by the engineer.
ADDITIONAL PROJECTS
Sentiment Analysis of Kannada Web Document
This project aims to analyze the sentiment of Kannada web documents using Machine Learning Algorithms.
Language: Python
Stemmer for Kannada Language in Information Retrieval System
This project aims to produce stemmer for Kannada language in Information Retrieval System.
Language: Java
Social Media Sentiment Analysis
This project aims to create a web application for social media analysis which provides analytics to analyze
Social media data like Facebook and Twitter.
Language: Java, SQL, JavaScript, HTML
Technologies: Fusion charts, facebook4j, GraphAPI, REST, twitter4j, AlchemyAPI
CERTIFICATES
Completed Core java, j2ee, HTML and SQL courses in JSpiders, Basavanagudi,
Bengaluru.
Responsibilities
JDeveloper
Drawing
Developed 'XREF Tool' using PL/SQL and Java. This is Internal tool for Oracle Retail product to
HOBBIES
06/2017 – 07/2019
07/2018 – 07/2019
mailto:pooj.vs@gmail.com

In [7]:
# I did this cause if i did it directly in the later part, and if he had any NaN value then it was giving output like : work experience of 0 year. which is wrong.
for i in range(1573):
  if pd.notnull(df['work_experience'][i]):
    df['work_experience'][i] = 'work experience of ' + ' ' + str(int(df['work_experience'][i])) + ' ' + 'year' #converted the float to str to concat

<ipython-input-7-2871a3316e95>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['work_experience'][i] = 'work experience of ' + ' ' + str(int(df['work_experience'][i])) + ' ' + 'year' #converted the float to str to concat

In [8]:
df['work_experience']

0                               NaN
1                               NaN
2                               NaN
3        work experience of  1 year
4                               NaN
                   ...
1568     work experience of  2 year
1569     work experience of  2 year
1570    work experience of  12 year
1571                            NaN
1572                            NaN
Name: work_experience, Length: 1573, dtype: object

In [9]:
# Combining relevant columns into a single text column for each resume. (Combined all the relevant columns which I thought are usefull in ranking resumes based on job description)
df['Content'] = (df['accomplishments_segment'].fillna('') + ' ' + #Did fillna to fill NaN values by empty string to concat it properly.
              df['degree'].fillna('') + ' ' +
              df['education_segment'].fillna('') + ' ' +
              df['job_titles'].fillna('') + ' ' +
              df['projects_segment'].fillna('') + ' ' +
              df['skills'].fillna('') + ' ' +
              df['skills_segment'].fillna('') + ' ' +
              df['text'].fillna('') + ' ' +
              df['work_experience'].fillna('') + ' ' +
              df['work_segment'].fillna(''))

In [10]:
df['Content'].head() #At the end got all the relevant content of the applicant in one single long string.

0     MS , B.TECH , PhD  full stack developer , stu...
1     B.E , MS , M.TECH M.Tech. Data Science\nJSS S...
2    Successfully cleared and completed the course ...
3     B.E , MS , BS  work from home , support analy...
4     MS , B.TECH , BS  work from home , classifier...
Name: Content, dtype: object

In [11]:
b = df["Content"][3]
print(str(b)) #Checking out how all info is concatenated. Looking for further preprocessing required.

 B.E , MS , BS  work from home , support analyst , software analyst , full time , associate software engineer  big data analytics , award , training , computer technology , matplotlib , algorithms , spark , nlp , case , hypothesis testing , pleasure , pandas , numpy , mumbai , edx , resume , datasets , java , machine learning , fundamentals , computer science , statistics , set theory , completion , assessment , probability , grounding , data science , python , one , computer engineering , ml , artificial intelligence , knowledge base , online  Assessment
Q1. Why should you be hired for this role?
After completing my Bachelor's degree in Computer Engineering back in 2017, I got hired in BNP Paribas ISPL as a Software Analyst in banking
reconciliations department and have worked there for more than 3 years. Ever since then, I had a deep interest in the field of Machine Learning
and Artificial Intelligence. One of my favorite activities at work was to automate manual tasks so that it saves the time of the team as a whole and
minimizes potential errors. Unfortunately, Machine Learning was not a part of my engineering syllabus and to expand my knowledge base about
the same, I enrolled myself in the edX Data Science Micromasters offered by University of California, San Diego. Since then, I have been working
on projects in Python as a part of the program and now have a comfortable level of familiarity with coding in Python. However, I am further
interested in working on projects where these techniques can be utilized to solve real world problems in a variety of domains. This will help me
increase my knowledge about these fields and at the same time provide hands-on experience through industry-level projects as well as
receiving guidance and feedback from mentors about possible improvements at work. I also checked the Boongg company website to find out
more about this and was greatly elated to learn about the various capabilities of the bike rental platform and it will be my pleasure to contribute
to this in any way possible. Furthermore, this internship is work from home which comes as a blessing in these trying times.
Q2. Are you available for 3 months, starting immediately, for a full-time work from home internship? If not, what is the time period you are
available for and the earliest date you can start this internship on?
Yes, I am available for 3 months, for a full time work from home internship, starting immediately.
Resume
EDUCAT ION
JOBS
TRAININGS
ADITYA THAKUR
Mumbai
Applied 08 Feb'21
 Python  Java  Machine Learning
Bachelor of Engineering B.E, Computer Science & Engineering
Watumull Institute Of Electronic Engineering And Computer Technology
2013 - 2017
CGPA 8.74/10
Senior Secondary XII, Science
Wilson College, Girgaum
HSC BOARD board)
Year of completion: 2013
Percentage: 84.33%
Secondary X
St. Xavier's High School, Fort
SSC board)
Year of completion: 2011
Percentage: 91.82%
Associate Support Analyst / Associate Software Engineer
BNP Paribas India Services Private Limited, Mumbai
Jun 2017 - Sep 2020
Worked on Intellimatch tool and handled requests for transaction reconciliation. Also built an automated alerts mechanism in
case of downtime BNPP Spot Award). Worked on reconciliations for Denver based clients BNPP Champion of the Month
award)
Data Science Micromasters
Edx UC San Diego), Online
Aug 2020 - Present
The microdegree is basically a MOOC offered by University of California, San Diego through EdX platform. It covers the
following topics:
(i) Python for DS training about Python language and tools like Numpy, Pandas, and Matplotlib as well as s ome ML and NLP
basics.
(ii) Probability and Statistics: topics such as Set Theory, Distributions and Hypothesis testing along with many others are
covered.
CONTACT Phone: 91 9930485336
(iii) Machine Learning Fundamentals: Intensive grounding about ML algorithms and using them to make predictions.
(iv) Big Data Analytics: Using Spark for handling massively parallelizable datasets. work experience of  1 year

In [12]:
# Converted all the text to lower
df['Content'] = df['Content'].str.lower()

In [13]:
b1 =df["Content"][3]
print(str(b1))

 b.e , ms , bs  work from home , support analyst , software analyst , full time , associate software engineer  big data analytics , award , training , computer technology , matplotlib , algorithms , spark , nlp , case , hypothesis testing , pleasure , pandas , numpy , mumbai , edx , resume , datasets , java , machine learning , fundamentals , computer science , statistics , set theory , completion , assessment , probability , grounding , data science , python , one , computer engineering , ml , artificial intelligence , knowledge base , online  assessment
q1. why should you be hired for this role?
after completing my bachelor's degree in computer engineering back in 2017, i got hired in bnp paribas ispl as a software analyst in banking
reconciliations department and have worked there for more than 3 years. ever since then, i had a deep interest in the field of machine learning
and artificial intelligence. one of my favorite activities at work was to automate manual tasks so that it saves the time of the team as a whole and
minimizes potential errors. unfortunately, machine learning was not a part of my engineering syllabus and to expand my knowledge base about
the same, i enrolled myself in the edx data science micromasters offered by university of california, san diego. since then, i have been working
on projects in python as a part of the program and now have a comfortable level of familiarity with coding in python. however, i am further
interested in working on projects where these techniques can be utilized to solve real world problems in a variety of domains. this will help me
increase my knowledge about these fields and at the same time provide hands-on experience through industry-level projects as well as
receiving guidance and feedback from mentors about possible improvements at work. i also checked the boongg company website to find out
more about this and was greatly elated to learn about the various capabilities of the bike rental platform and it will be my pleasure to contribute
to this in any way possible. furthermore, this internship is work from home which comes as a blessing in these trying times.
q2. are you available for 3 months, starting immediately, for a full-time work from home internship? if not, what is the time period you are
available for and the earliest date you can start this internship on?
yes, i am available for 3 months, for a full time work from home internship, starting immediately.
resume
educat ion
jobs
trainings
aditya thakur
mumbai
applied 08 feb'21
 python  java  machine learning
bachelor of engineering b.e, computer science & engineering
watumull institute of electronic engineering and computer technology
2013 - 2017
cgpa 8.74/10
senior secondary xii, science
wilson college, girgaum
hsc board board)
year of completion: 2013
percentage: 84.33%
secondary x
st. xavier's high school, fort
ssc board)
year of completion: 2011
percentage: 91.82%
associate support analyst / associate software engineer
bnp paribas india services private limited, mumbai
jun 2017 - sep 2020
worked on intellimatch tool and handled requests for transaction reconciliation. also built an automated alerts mechanism in
case of downtime bnpp spot award). worked on reconciliations for denver based clients bnpp champion of the month
award)
data science micromasters
edx uc san diego), online
aug 2020 - present
the microdegree is basically a mooc offered by university of california, san diego through edx platform. it covers the
following topics:
(i) python for ds training about python language and tools like numpy, pandas, and matplotlib as well as s ome ml and nlp
basics.
(ii) probability and statistics: topics such as set theory, distributions and hypothesis testing along with many others are
covered.
contact phone: 91 9930485336
(iii) machine learning fundamentals: intensive grounding about ml algorithms and using them to make predictions.
(iv) big data analytics: using spark for handling massively parallelizable datasets. work experience of  1 year

In [14]:
import unicodedata

# There are various symobls in the text.
# Took the range of such char, and compared it with each char and accordingly appended clean char and later joined them into a single string.
def remove_pua_symbols(text):
    cleaned_text = []
    for char in text:
        if ord(char) < 0xE000 or ord(char) > 0xF8FF:
            cleaned_text.append(char)
    return ''.join(cleaned_text)

# Apply the function to 'Content' column
df['Content'] = df['Content'].apply(remove_pua_symbols)

In [15]:
b1 =df["Content"][3]
print(str(b1))

 b.e , ms , bs  work from home , support analyst , software analyst , full time , associate software engineer  big data analytics , award , training , computer technology , matplotlib , algorithms , spark , nlp , case , hypothesis testing , pleasure , pandas , numpy , mumbai , edx , resume , datasets , java , machine learning , fundamentals , computer science , statistics , set theory , completion , assessment , probability , grounding , data science , python , one , computer engineering , ml , artificial intelligence , knowledge base , online  assessment
q1. why should you be hired for this role?
after completing my bachelor's degree in computer engineering back in 2017, i got hired in bnp paribas ispl as a software analyst in banking
reconciliations department and have worked there for more than 3 years. ever since then, i had a deep interest in the field of machine learning
and artificial intelligence. one of my favorite activities at work was to automate manual tasks so that it saves the time of the team as a whole and
minimizes potential errors. unfortunately, machine learning was not a part of my engineering syllabus and to expand my knowledge base about
the same, i enrolled myself in the edx data science micromasters offered by university of california, san diego. since then, i have been working
on projects in python as a part of the program and now have a comfortable level of familiarity with coding in python. however, i am further
interested in working on projects where these techniques can be utilized to solve real world problems in a variety of domains. this will help me
increase my knowledge about these fields and at the same time provide hands-on experience through industry-level projects as well as
receiving guidance and feedback from mentors about possible improvements at work. i also checked the boongg company website to find out
more about this and was greatly elated to learn about the various capabilities of the bike rental platform and it will be my pleasure to contribute
to this in any way possible. furthermore, this internship is work from home which comes as a blessing in these trying times.
q2. are you available for 3 months, starting immediately, for a full-time work from home internship? if not, what is the time period you are
available for and the earliest date you can start this internship on?
yes, i am available for 3 months, for a full time work from home internship, starting immediately.
resume
educat ion
jobs
trainings
aditya thakur
mumbai
applied 08 feb'21
 python  java  machine learning
bachelor of engineering b.e, computer science & engineering
watumull institute of electronic engineering and computer technology
2013 - 2017
cgpa 8.74/10
senior secondary xii, science
wilson college, girgaum
hsc board board)
year of completion: 2013
percentage: 84.33%
secondary x
st. xavier's high school, fort
ssc board)
year of completion: 2011
percentage: 91.82%
associate support analyst / associate software engineer
bnp paribas india services private limited, mumbai
jun 2017 - sep 2020
worked on intellimatch tool and handled requests for transaction reconciliation. also built an automated alerts mechanism in
case of downtime bnpp spot award). worked on reconciliations for denver based clients bnpp champion of the month
award)
data science micromasters
edx uc san diego), online
aug 2020 - present
the microdegree is basically a mooc offered by university of california, san diego through edx platform. it covers the
following topics:
(i) python for ds training about python language and tools like numpy, pandas, and matplotlib as well as s ome ml and nlp
basics.
(ii) probability and statistics: topics such as set theory, distributions and hypothesis testing along with many others are
covered.
contact phone: 91 9930485336
(iii) machine learning fundamentals: intensive grounding about ml algorithms and using them to make predictions.
(iv) big data analytics: using spark for handling massively parallelizable datasets. work experience of  1 year

In [16]:
#Used tf-idf vectorizer to convert it into vectors, removing common english stopwards.
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(df['Content'])

In [17]:
job_description = """We are looking for an experienced AI Engineer for a
client project which is specializing in fraud detection using Large Language Models (LLMs) and traditional
machine learning models. This role will involve
designing and developing cutting-edge AI solutions for
client projects while contributing to future-focused
prediction and insights products. The role will evolve to
work in other domains including healthcare where ever
insights and decision making can be done using AI.
Collaborate with cross-functional teams to
understand client requirements and translate
them into scalable AI models.
Design, develop, and implement fraud detection
models using LLMs and traditional machine
learning techniques.
Build and maintain data pipelines for training,
testing, and deploying models efficiently.
Develop prediction and insights tools to provide
actionable intelligence for fraud prevention.
Python, LangChain, LlamaIndex,
pandas, ML algorithms, AI algorithms, Fine
Tuning, REST APIS

"""

In [18]:
job_desc_vector = vectorizer.transform([job_description.lower()]) #Converted JD to vectors for comparing similarity.

In [19]:
# Calculated similarity scores
from sklearn.metrics.pairwise import cosine_similarity
df['similarity'] = cosine_similarity(X, job_desc_vector).flatten()

# Ranked resumes based on similarity scores
df = df.sort_values(by='similarity', ascending=False)

# Displayed top 5 ranked resumes
df[['name', 'similarity']].head()

                   name  similarity
148       FAZAL JAMADAR    0.192490
986     System Engineer    0.178397
1338  Solution Delivery    0.160257
668      Waqqas Khusraw    0.157733
413   Priyansh Bhardwaj    0.157464

In [21]:
job_description2 = """We are seeking a highly motivated and analytical Data Analyst to join our team. You will be responsible for collecting, cleaning, analyzing, and visualizing data to identify trends, patterns, and insights that inform business decisions. You will work closely with stakeholders across the organization to translate data into actionable recommendations and reports.
Collect and extract data from various sources, including databases, APIs, and web scraping.
Clean and prepare data for analysis, including identifying and correcting errors, inconsistencies, and missing values.
Perform statistical analysis and data mining to identify trends, patterns, and relationships.
Develop and maintain data pipelines and automation processes.
Create data visualizations using tools like Tableau, Power BI, or Excel to communicate insights effectively.
Generate reports and presentations to communicate findings to stakeholders.
Collaborate with cross-functional teams to define data requirements and translate data insights into actionable recommendations.
Stay up-to-date on the latest data analysis techniques and tools.
Bachelor's degree in Statistics, Mathematics, Computer Science, Business Analytics, or a related field.
2+ years of experience in a data analyst role.
Strong analytical and problem-solving skills.
Proficiency in SQL and Python, R.
Excellent data visualization and communication skills.
Ability to work independently and as part of a team.
Experience with machine learning and data mining algorithms.
Experience with cloud platforms AWS, Azure.
Knowledge of specific industry finance, healthcare, marketing.
"""

In [22]:
job_desc_vector2 = vectorizer.transform([job_description2.lower()])

In [23]:
df['similarity'] = cosine_similarity(X, job_desc_vector2).flatten()

df = df.sort_values(by='similarity', ascending=False)

df[['name', 'similarity']].head()

              name  similarity
1307  Cloud Devops    0.263037
1270    IT Project    0.246825
594   Sushil Kumar    0.246754
701    IT Software    0.245117
429     Rakesh Das    0.236174

In [26]:
#Defined a function to do the same things as above for the user input.
def get_relevant_resumes(job_description,df):

  job_desc_vector = vectorizer.transform([job_description.lower()])

  df['similarity'] = cosine_similarity(X, job_desc_vector).flatten()

  df = df.sort_values(by='similarity', ascending=False)

  return df[['name', 'similarity']].head()

In [27]:
# User Input for the JD
job_description = input("Enter the job description: ")

relevant_resumes = get_relevant_resumes(job_description,df)

#Printing the relevant resumes
print("Top 5 relevant resumes:")
print(relevant_resumes)

Enter the job description: Enter the job description: We are seeking a passionate and talented UI/UX Designer to join our growing team. You will be responsible for the entire user experience, from research and ideation to prototyping and implementation. You will work closely with cross-functional teams, including product managers, engineers, and marketers, to create intuitive and engaging interfaces that meet our users' needs.Conduct user research and analysis to understand user needs and pain points.Develop user personas and journey maps. Design wireframes, prototypes, and mockups. Create user interface elements that are visually appealing and easy to use. Ensure designs are consistent with brand guidelines and accessibility standards. Collaborate with developers to implement designs. Conduct usability testing and iterate on designs based on user feedback. Stay up-to-date on the latest UI/UX trends and technologies.3+ years of experience in UI/UX design. Strong portfolio showcasing a variety of design projects. Proven experience with user research and usability testing. Proficiency in design tools such as Figma, Sketch, and Adobe XD. Excellent communication and collaboration skills. Ability to work independently and as part of a team.Experience with front-end development, Knowledge of accessibility best practices, and Experience with design thinking methodologies.
Top 5 relevant resumes:
                     name  similarity
511               Pvt Ltd    0.362014
330         Deep Learning    0.285377
164          Data Science    0.258391
1260  Technical Solutions    0.225724
409             Priti Nil    0.191581